### ISSUE TITLE
Header in app error message 'Unknown identity' shows logo/text mixed up

### ISSUE THREAD

**Issue by eefjevanderharst** [SURFnet/tiqr-client-ios#17] opened 2016-10-05 08:47 UTC
In the error messages 'Unknown identity, please enrol first.' the header of the tiqr app shows both the tiqr logo as the text 'Login'. The  header should only show the text 'Login'. Please remove the logo.
See attached image
![tiqr error jpg](https://cloud.githubusercontent.com/assets/8789958/19106694/11f1a12c-8ae9-11e6-98ff-80a83a6db3d2.png)

**Comment by joostd** [comment] 2016-10-05 14:09
I cannot reproduce this screen. Where did you try to authenticate? What version of iOS are you using?

**Comment by eefjevanderharst** [comment] 2016-10-26 07:51
When user has removed its tiqr-ID in the tiqr app, but still tries to authenticatie afterwards. Push notifications will no longer work once tiqr-id has been removed (as expected), so I use the 'scan QR code'  method as an alternative. But since the tiqr-ID is missing in the app, it cannot map the ID anymore with the QR code. 
Tested with iOS 10.1 , Tiqr app v2.5 with demo SP of http://pieter.aai.surfnet.nl/

**Comment by thijskh** [comment] 2016-12-24 06:18
Confirmed that this is fixed in build 42.

**Closed** 2017-03-24 08:56 UTC
